# group_vars/all.yml

# Static folder where certs live (control node)
cert_dir: "/home/student/project/nssa320g7/cert"

# Expected certificate files
server_key_path: "{{ cert_dir }}/winrm_server.key"
server_crt_path: "{{ cert_dir }}/winrm_server.crt"
server_pfx_path: "{{ cert_dir }}/winrm_server.pfx"
server_csr_path: "{{ cert_dir }}/winrm_server.csr"

# CA files
ca_cert_path: "{{ cert_dir }}/ca.pem"
ca_key_file: "{{ cert_dir }}/ca.key"

# Windows server certificate length
server_cert_days: 365

# OpenSSL extension file for CSR signing
openssl_ext_path: "{{ cert_dir }}/winrm_ext.conf"
